name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.AWS_HOST}}
            USER_NAME: ${{secrets.AWS_USERNAME}}
      
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.AWS_USERNAME}}@${{secrets.AWS_HOST}} '
            # Now we have got the access of EC2 and we will start the deploy .
            cd /project/binar-chpt-8/challange-7-FE &&
            git pull origin main
            npm install --force
            pm2 restart fe-challange-8
